Naive Bayes

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [ ]:
dataset=pd.read_csv('/content/cardio.csv')
dataset

ind  sbp  tobacco    ldl  adiposity  famhist  typea  obesity  alcohol  \
0      1  160    12.00   5.73      23.11  Present     49    25.30    97.20   
1      2  144     0.01   4.41      28.61   Absent     55    28.87     2.06   
2      3  118     0.08   3.48      32.28  Present     52    29.14     3.81   
3      4  170     7.50   6.41      38.03  Present     51    31.99    24.26   
4      5  134    13.60   3.50      27.78  Present     60    25.99    57.34   
..   ...  ...      ...    ...        ...      ...    ...      ...      ...   
457  459  214     0.40   5.98      31.72   Absent     64    28.45     0.00   
458  460  182     4.20   4.41      32.10   Absent     52    28.61    18.72   
459  461  108     3.00   1.59      15.23   Absent     40    20.09    26.64   
460  462  118     5.40  11.61      30.79   Absent     64    27.35    23.97   
461  463  132     0.00   4.82      33.41  Present     62    14.70     0.00   

     age  chd  
0     52    1  
1     63    1  
2     46    0  
3     58    1  
4     49    1  
..   ...  ...  
457   58    0  
458   52    1  
459   55    0  
460   40    0  
461   46    1  

[462 rows x 11 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ind        462 non-null    int64  
 1   sbp        462 non-null    int64  
 2   tobacco    462 non-null    float64
 3   ldl        462 non-null    float64
 4   adiposity  462 non-null    float64
 5   famhist    462 non-null    object 
 6   typea      462 non-null    int64  
 7   obesity    462 non-null    float64
 8   alcohol    462 non-null    float64
 9   age        462 non-null    int64  
 10  chd        462 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 39.8+ KB


In [ ]:
dataset.isna().sum()

ind          0
sbp          0
tobacco      0
ldl          0
adiposity    0
famhist      0
typea        0
obesity      0
alcohol      0
age          0
chd          0
dtype: int64

In [ ]:
dataset.columns

Index(['ind', 'sbp', 'tobacco', 'ldl', 'adiposity', 'famhist', 'typea',
       'obesity', 'alcohol', 'age', 'chd'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
dataset['famhist']=lb.fit_transform(dataset['famhist'])
dataset

ind  sbp  tobacco    ldl  adiposity  famhist  typea  obesity  alcohol  \
0      1  160    12.00   5.73      23.11        1     49    25.30    97.20   
1      2  144     0.01   4.41      28.61        0     55    28.87     2.06   
2      3  118     0.08   3.48      32.28        1     52    29.14     3.81   
3      4  170     7.50   6.41      38.03        1     51    31.99    24.26   
4      5  134    13.60   3.50      27.78        1     60    25.99    57.34   
..   ...  ...      ...    ...        ...      ...    ...      ...      ...   
457  459  214     0.40   5.98      31.72        0     64    28.45     0.00   
458  460  182     4.20   4.41      32.10        0     52    28.61    18.72   
459  461  108     3.00   1.59      15.23        0     40    20.09    26.64   
460  462  118     5.40  11.61      30.79        0     64    27.35    23.97   
461  463  132     0.00   4.82      33.41        1     62    14.70     0.00   

     age  chd  
0     52    1  
1     63    1  
2     46    0  
3     58    1  
4     49    1  
..   ...  ...  
457   58    0  
458   52    1  
459   55    0  
460   40    0  
461   46    1  

[462 rows x 11 columns]

In [ ]:
x=dataset.drop(["chd"],axis=1)
x.head()

ind  sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age
0    1  160    12.00  5.73      23.11        1     49    25.30    97.20   52
1    2  144     0.01  4.41      28.61        0     55    28.87     2.06   63
2    3  118     0.08  3.48      32.28        1     52    29.14     3.81   46
3    4  170     7.50  6.41      38.03        1     51    31.99    24.26   58
4    5  134    13.60  3.50      27.78        1     60    25.99    57.34   49

In [ ]:
y=dataset["chd"]
y.head()

0    1
1    1
2    0
3    1
4    1
Name: chd, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)
classifier = GaussianNB()
classifier.fit (x_train, y_train) 

GaussianNB()

In [ ]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0])

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[47 14]
 [14 18]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77        61
           1       0.56      0.56      0.56        32

    accuracy                           0.70        93
   macro avg       0.67      0.67      0.67        93
weighted avg       0.70      0.70      0.70        93



In [ ]:
akurasi = accuracy_score(y_test,y_pred)
akurasi

0.6989247311827957

In [ ]:
from sklearn.naive_bayes import GaussianNB
k=10
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import GridSearchCV
params = {}
NB = StratifiedGroupKFold (n_splits=k)
NB2 = GridSearchCV(GaussianNB(), cv=NB, param_grid=params)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import classification_report
from sklearn import metrics

y_pred = cross_val_predict (NB2,x,y,cv=10)
score=cross_val_score(NB2,x,y,cv=10,scoring='accuracy')
confussion_matrix_NB=pd.crosstab(y,y_pred, rownames = ['Actual'],colnames = ['predict'])
report_NB=classification_report(y,y_pred)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:774: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_scorer.py", line 418, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 651, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 82, in predict
    X = self._check_X(X)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py", line 251, in _check_X
    return self._validate_data(X, reset=False)
  File "/usr/local/lib/python3.7/dist-

In [ ]:
print(confussion_matrix_NB)

predict    0    1
Actual           
0        228   74
1         59  101


In [ ]:
print(report_NB)

              precision    recall  f1-score   support

           0       0.79      0.75      0.77       302
           1       0.58      0.63      0.60       160

    accuracy                           0.71       462
   macro avg       0.69      0.69      0.69       462
weighted avg       0.72      0.71      0.71       462



In [ ]:
print("accuracy = ",score.mean()*100,"%")

accuracy =  71.22109158186865 %


svm

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
#K-FOLD CROSS VALIDATION
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((369, 10), (93, 10), (369,), (93,))

In [ ]:
model = SVC(kernel='poly')
model.fit(x_train, y_train)

SVC(kernel='poly')

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
print(accuracy_score(y_test, y_pred))

0.6129032258064516


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.61      1.00      0.76        57
           1       0.00      0.00      0.00        36

    accuracy                           0.61        93
   macro avg       0.31      0.50      0.38        93
weighted avg       0.38      0.61      0.47        93



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix
res = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(res)

Confusion Matrix
[[57  0]
 [36  0]]


In [ ]:
#Percentage split
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

In [ ]:
model_SVM_cv = SVC(kernel='poly')
score_SVM_cv = cross_val_score(model_SVM_cv, x, y, cv=10, scoring='accuracy')
y_pred_SVM_cv = cross_val_predict(model_SVM_cv, x, y, cv=10)
report_SVM_cv = classification_report(y, y_pred_SVM_cv)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
res2 = confusion_matrix(y, y_pred_SVM_cv)
print("Confusion Matrix")
print(res2)

Confusion Matrix
[[302   0]
 [160   0]]


In [ ]:
print(report_SVM_cv)

              precision    recall  f1-score   support

           0       0.65      1.00      0.79       302
           1       0.00      0.00      0.00       160

    accuracy                           0.65       462
   macro avg       0.33      0.50      0.40       462
weighted avg       0.43      0.65      0.52       462



In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y, y_pred_SVM_cv))

0.6536796536796536


Klasifikasi KNN

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2)

In [ ]:
import sklearn
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

k=10
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 1, ..., 0, 1, 1])

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[5104 1915]
 [3187 3794]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.73      0.67      7019
           1       0.66      0.54      0.60      6981

    accuracy                           0.64     14000
   macro avg       0.64      0.64      0.63     14000
weighted avg       0.64      0.64      0.63     14000



In [ ]:
akurasi = accuracy_score(y_test,y_pred)
akurasi

0.6559139784946236

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
k=5

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=k)

y_pred = cross_val_predict (model,x,y,cv=5)
score=cross_val_score(model,x,y,cv=5,scoring='accuracy')
confussion_knn=pd.crosstab(y,y_pred, rownames = ['Actual'],colnames = ['predict'])
report_knn=classification_report(y,y_pred)

In [ ]:
print(confussion_knn)

predict    0    1
Actual           
0        203  146
1        162  199


In [ ]:
print(report_knn)

              precision    recall  f1-score   support

           0       0.56      0.58      0.57       349
           1       0.58      0.55      0.56       361

    accuracy                           0.57       710
   macro avg       0.57      0.57      0.57       710
weighted avg       0.57      0.57      0.57       710



In [ ]:
print("Accuracy : ",score.mean()*100, "%")

Accuracy :  56.619718309859145 %
